dtb-$(CONFIG_ARCH_SUN50IW3P1) += sun50iw3p1-fpga.dtb sun50iw3p1-soc.dtb \
				sun50iw3p1-perf1_v1_0.dtb sun50iw3p1-perf2_v1_0.dtb \
				sun50iw3p1-y1.dtb sun50iw3p1-t1.dtb

dtb-$(CONFIG_ARCH_SUN50IW1P1) += sun50iw1p1-fpga.dtb  sun50iw1p1-perf1_v1_0.dtb \
				sun50iw1p1-perf2_v1_0.dtb sun50iw1p1-t1.dtb \
				sun50iw1p1-sata.dtb sun50iw1p1-soc.dtb

dtb-$(CONFIG_ARCH_SUN50IW6P1) += sun50iw6p1-soc.dtb tm3-tm3.dtb tm3-tmxdevboard.dtb tm3-hb5.dtb \
				tm3-hb5-43-c.dtb \
				tm3-hb5-43-r.dtb \
				tm3-hb5-12-c.dtb \
				tm3-hb5-7-c.dtb \
				tm3-hb5-7-r.dtb \
				tm3-hb5-9-c.dtb \
				tm3-hb5-cb3-43-c.dtb \
				tm3-hb5-cb3-43-r.dtb \
				tm3-hb5-cb3-12-c.dtb \
				tm3-hb5-cb3-7-c.dtb \
				tm3-hb5-cb3-7-r.dtb \
				tm3-hb5-cb3-9-c.dtb \
				tm3-hb5-cb3-9-c.dtb \
				tm3-hbpicm4-cm4io.dtb


dtb-$(CONFIG_ARCH_SUN50IW8P1) += sun50iw8p1-fpga.dtb sun50iw8p1-soc.dtb
dtb-$(CONFIG_ARCH_SUN50IW5T) += sun50iw5t-fpga.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
